[package]
name = "notegen"
version = "0.9.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^3.1.6", features = ["derive"] }
regex = "^1.5.5"
dirs = "^4.0.0"
