[package]
name = "notegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown-gen = "^1.2.1"
clap = { version = "^3.1.6", features = ["derive"] }
regex = "^1.5.5"
dirs = "^4.0.0"